### ISSUE TITLE
implementation of diopt() missing from the package?

### ISSUE THREAD

**Issue by pedriniedoardo** [oganm/homologene#16]
the function diopt() seems to be missing from the package (CRAN version).

**Comment by oganm** [comment]
Yes. I didn't push a CRAN update to add the diopt function since I wasn't sure I would keep the function as it is. It doesn't/can't exactly use best practices since DIOPT doesn't has an API and the function works by filling the webform.

You can still use the github version of the package though. The next update to the CRAN version will probably have the function in some form

**Comment by pedriniedoardo** [comment]
I see, thank you for the feedback and for the VERY useful package!
